<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Follow Development</h3>
        </div>
        <div class="panel-body">
            <p>
                Zend Framework is under active development. If you are
                interested in following the development of ZF, you can check
                <a href="http://framework.zend.com/blog/">ZF dev blog</a>,
                and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:zendframework">ZF issue tracker</a>
                (link requires a GitHub account). This is a great resource
                for staying up to date with the latest developments!
            </p>

            <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Development Portal &raquo;</a></p>
        </div>
    </div>
</div>